
'use server';
/**
 * @fileOverview A flow to handle real-money withdrawals via MTN Mobile Money Sandbox API.
 *
 * - processMomoWithdrawal - A server-side function to securely process a withdrawal request.
 * - MomoWithdrawalInput - The input type for the processMomoWithdrawal function.
 * - MomoWithdrawalOutput - The return type for the processMomoWithdrawal function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { crypto } from 'crypto';

const MomoWithdrawalInputSchema = z.object({
  amount: z.number().describe('The amount of GHS to withdraw.'),
  momoNumber: z.string().describe('The 10-digit MTN Mobile Money number to send funds to.'),
  transactionId: z.string().describe('A unique ID for this transaction, generated by the client.'),
});
export type MomoWithdrawalInput = z.infer<typeof MomoWithdrawalInputSchema>;

const MomoWithdrawalOutputSchema = z.object({
  success: z.boolean().describe('Whether the withdrawal was successfully processed.'),
  message: z.string().describe('A message detailing the result of the operation.'),
  providerTransactionId: z.string().optional().describe('The provider transaction ID, if successful.'),
});
export type MomoWithdrawalOutput = z.infer<typeof MomoWithdrawalOutputSchema>;

/**
 * Helper to get a Sandbox Access Token from MTN
 */
async function getMomoAccessToken(apiUserId: string, apiKey: string, subscriptionKey: string) {
  const auth = Buffer.from(`${apiUserId}:${apiKey}`).toString('base64');
  
  const response = await fetch('https://sandbox.momodeveloper.mtn.com/disbursement/token/', {
    method: 'POST',
    headers: {
      'Authorization': `Basic ${auth}`,
      'Ocp-Apim-Subscription-Key': subscriptionKey,
    },
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`MTN Auth Error: ${errorText || response.statusText}`);
  }

  const data = await response.json();
  return data.access_token;
}

export async function processMomoWithdrawal(input: MomoWithdrawalInput): Promise<MomoWithdrawalOutput> {
  return momoWithdrawalFlow(input);
}

const momoWithdrawalFlow = ai.defineFlow(
  {
    name: 'momoWithdrawalFlow',
    inputSchema: MomoWithdrawalInputSchema,
    outputSchema: MomoWithdrawalOutputSchema,
  },
  async (input) => {
    const { amount, momoNumber } = input;

    const apiUserId = process.env.MTN_API_USER_ID;
    const apiKey = process.env.MTN_API_KEY;
    const subscriptionKey = process.env.MTN_SUBSCRIPTION_KEY;

    if (!apiUserId || !apiKey || !subscriptionKey || subscriptionKey.includes('PASTE_YOUR')) {
      return {
        success: false,
        message: 'Withdrawal failed: MTN API credentials or Subscription Key are missing or invalid in .env.',
      };
    }

    try {
      const accessToken = await getMomoAccessToken(apiUserId, apiKey, subscriptionKey);
      const referenceId = crypto.randomUUID();

      const transferBody = {
        amount: amount.toString(),
        currency: "EUR", 
        externalId: input.transactionId,
        payee: {
          partyIdType: "MSISDN",
          partyId: momoNumber.startsWith('233') ? momoNumber : `233${momoNumber.replace(/^0/, '')}`
        },
        payerMessage: "EarnBull Withdrawal",
        payeeNote: "Transfer from EarnBull wallet"
      };

      const transferResponse = await fetch('https://sandbox.momodeveloper.mtn.com/disbursement/v1_0/transfer', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'X-Reference-Id': referenceId,
          'X-Target-Environment': 'sandbox',
          'Content-Type': 'application/json',
          'Ocp-Apim-Subscription-Key': subscriptionKey,
        },
        body: JSON.stringify(transferBody),
      });

      if (transferResponse.status === 202) {
        return {
          success: true,
          message: `Withdrawal of GHS ${amount} initiated successfully.`,
          providerTransactionId: referenceId,
        };
      } else {
        const errorData = await transferResponse.text();
        return {
          success: false,
          message: `MTN Transfer Error: ${errorData || transferResponse.statusText}`,
        };
      }
    } catch (error: any) {
      return {
        success: false,
        message: error.message || 'An unexpected error occurred during withdrawal.',
      };
    }
  }
);
