'use server';
/**
 * @fileOverview A flow to handle real-money withdrawals via MTN Mobile Money.
 *
 * - processMomoWithdrawal - A server-side function to securely process a withdrawal request.
 * - MomoWithdrawalInput - The input type for the processMomoWithdrawal function.
 * - MomoWithdrawalOutput - The return type for the processMomoWithdrawal function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const MomoWithdrawalInputSchema = z.object({
  amount: z.number().describe('The amount of GHS to withdraw.'),
  momoNumber: z.string().describe('The 10-digit MTN Mobile Money number to send funds to.'),
  transactionId: z.string().describe('A unique ID for this transaction, generated by the client.'),
});
export type MomoWithdrawalInput = z.infer<typeof MomoWithdrawalInputSchema>;

const MomoWithdrawalOutputSchema = z.object({
  success: z.boolean().describe('Whether the withdrawal was successfully processed.'),
  message: z.string().describe('A message detailing the result of the operation.'),
  providerTransactionId: z.string().optional().describe('The provider transaction ID, if successful.'),
});
export type MomoWithdrawalOutput = z.infer<typeof MomoWithdrawalOutputSchema>;

export async function processMomoWithdrawal(input: MomoWithdrawalInput): Promise<MomoWithdrawalOutput> {
  return momoWithdrawalFlow(input);
}

const momoWithdrawalFlow = ai.defineFlow(
  {
    name: 'momoWithdrawalFlow',
    inputSchema: MomoWithdrawalInputSchema,
    outputSchema: MomoWithdrawalOutputSchema,
  },
  async (input) => {
    console.log('Attempting MoMo withdrawal with input:', input);

    const { amount, momoNumber, transactionId } = input;

    // IMPORTANT: These API keys must be set in your .env file.
    const apiUserId = process.env.MTN_API_USER_ID;
    const apiKey = process.env.MTN_API_KEY;
    const subscriptionKey = process.env.MTN_SUBSCRIPTION_KEY;

    if (!apiUserId || !apiKey || !subscriptionKey) {
      console.error('MTN API credentials are not configured in .env file.');
      return {
        success: false,
        message: 'Server configuration error: API credentials for payment provider are missing.',
      };
    }

    // =================================================================================
    // THIS IS A MOCK API CALL.
    // You will need to replace this with the actual API call to the MTN Disbursement API.
    // This will involve using `fetch` to POST to the correct MTN endpoint with the
    // required headers (like Ocp-Apim-Subscription-Key) and body payload.
    // You will also need to handle authentication (e.g., getting an access token).
    // =================================================================================
    
    console.log('Simulating API call to MTN Mobile Money...');
    
    // Mocking a successful API response after a short delay.
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const mockApiSuccess = true; // Change to `false` to test failure scenarios.
    
    if (mockApiSuccess) {
      console.log('Mock API call successful.');
      return {
        success: true,
        message: `Successfully processed withdrawal of GHS ${amount} to ${momoNumber}.`,
        providerTransactionId: `MOCK_TX_${Date.now()}`,
      };
    } else {
      console.log('Mock API call failed.');
      return {
        success: false,
        message: 'The payment provider declined the transaction.',
      };
    }
  }
);
